### ISSUE TITLE
Playlist does not register as "stopped" after retrigger plays next item

### ISSUE THREAD

**Issue by seanmcnally98** [mko1989/acCompaniment#12]
The new retrigger behavior "Play Next Item (Playlist Only)" is incredible, it does exactly what I need it to.  But there is a bug, when you retrigger to the next item and that next item ends, the program does not register that it ever stopped playing.  It gets stuck in "playing" mode (green), reports that it's playing to companion, and nothing, not even the panic button, can reset it to stopped.

**Comment by mko1989** [comment]
Do you mean the stuck playing state only in companion or also in the app?

**Comment by seanmcnally98** [comment]
It is both, the app also shows it as playing

**Comment by mko1989** [comment]
Ok. Adding to the list.

**Comment by mko1989** [comment]
should be fixed. let me know if it is for you too.

**Comment by seanmcnally98** [comment]
Hm...doesn't seem to be fixed yet on 1.0.3

https://github.com/user-attachments/assets/de7f65dd-4484-4c49-bd54-f3d8bdb9f634

**Comment by mko1989** [comment]
Can you try v1.1.0 and see if the issue is fixed for you?

**Comment by seanmcnally98** [comment]
Thanks for your work on this!  It is half-fixed right now as a new, related bug seems to have been introduced.  Every item in a playlist seems to work fine **except for the last item.**  All other items will successfully stop whether a retrigger occurs, or the item preceding it naturally ends.  But the final item in a playlist will still get stuck in the "playing" state no matter what you do. See the video below for a demo:

**Version 1.1.0:**

https://github.com/user-attachments/assets/ce0d26d6-e9d9-4041-819e-071722ddf6ee

**Comment by mko1989** [comment]
Can you please check in v1.1.1 if the issue is gone?

**Comment by seanmcnally98** [comment]
The issue has changed but isn't fixed.  I'm on V1.1.1 of AcCompaniment and V1.2.1 of the module.  The issue is fixed in the main GUI of acCompaniment, but it is not fixed in Companion.  The exact same bug occurs where the last item of a playlist gets stuck in the "playing" state according to Companion.  

Additionally, as of 1.1.1, all single-item cues get stuck in the "playing" state in the GUI when they reach the end, but funny enough, they work fine in companion.  The GUI reports them as playing (green) after they end, companion reports them as stopped.

One other note - "stop all" really should reset these states, but doesn't.  If something gets stuck in the "playing" state despite the fact it is stopped, "Stop all" does not help you.

**Comment by mko1989** [comment]
Forgot to check companion and haven't even thought that single cues started doing that.
should be all fixed in v1.1.3
please let me know.
If you have any other ideas for improvments let me know.

As to stop all note. Those were bugs in the code, thats why the stop all didnt fix it as for the app it read as stopped.

**Comment by seanmcnally98** [comment]
This has been fixed!  Thanks so much for your work on this, I plan to use this program a lot so I will definitely let you know if I come up with any other ideas for new features.
